### ISSUE TITLE
Syntax not set properly

### ISSUE THREAD

**Issue by gilgen** [mustache/vim-mustache-handlebars#2]
This might sound like an odd question, but I can't seem to get the syntax highlighting to take. If I manually do a `:set syntax=mustache` the example.mustache gets highlighted properly. Right now, it seems to be defaulting to html syntax even when I try to set the syntax explicitly in an `au BufReadPost *.hbs set syntax=mustache` in my .vimrc.

**Comment by CreativLogic** [comment]
I have this problem as well and only found the solution to add this line to my `.vimrc`:

```
au BufReadPost *.hbs set filetype=html.mustache syntax=html.mustache
```

**Comment by jesenko** [comment]
I had the similar issue - for some '.hbs' files syntax did not get set to `mustache`. After disabling plugins one by one, I found that [restore-view.vim](https://github.com/vim-scripts/restore_view.vim) plugin was messing things up. After disabling this plugin, setting the syntax started working again. I did not look into details of what the underlying problem was...

**Comment by KaoruDev** [comment]
@CreativLogic :+1:  worked for me
