### ISSUE TITLE
Causes indentation issues

### ISSUE THREAD

**Issue by alexlafroscia** [mustache/vim-mustache-handlebars#45]
This plugin seems to do some weird things with indentation, which I am always fighting against.  For example, if I have some code that looks like this: (`_` denotes location of the cursor):

``` handlebars
<div class='container'>
  <h2 id="title">Welcome to Ember</h2>_

  {{outlet}}
</div>
```

and then press `RETURN` twice, what I want is for the file to look like this:

``` handlebars
<div class='container'>
  <h2 id="title">Welcome to Ember</h2>

  _

  {{outlet}}
</div>
```

However, for some reason, it messes with the location of the `<h2>` tag, removing its indentation.  So, instead, the files ends up like this instead:

``` handlebars
<div class='container'>
<h2 id="title">Welcome to Ember</h2>

_

  {{outlet}}
</div>
```

every time this happens, I end up having to leave insert mode, go back up to the line that moved itself, and then re-indent this line.  Why does the plugin do this?  Is this something that can be turned off?

**Edit:** This also, more annoyingly, seems to happen when editing between a tag as well.  For example, if you have something like this:

``` hbs
<div class='container'>
  <h2 id="title">_</h2>

  {{outlet}}
</div>
```

and press `RETURN`, you now get this:

``` hbs
<div class='container'>
<h2 id="title">
_
</h2>

  {{outlet}}
</div>
```

which now requires you to fix the indentation on multiple lines.

**Comment by JemBijoux** [comment]
This is probably very related to #40. The indenting in general is not working great.

No response here in over 2 months, even longer for that other issue. I use hdbs a lot in my day to day and want to get this productive in vim... looks like maybe I've gotta learn vimscript.

**Comment by alexlafroscia** [comment]
Yeah, definitely looks related.

**Comment by AndrewRadev** [comment]
@alexlafroscia I'm not one of the maintainers of the plugin, but maybe I can help you debug the issue. Could you give me some more info?

- What is the extension of the file you're testing? I'm asking, because "hbs" and "mustache" files get marked as slightly different filetypes. You can find the actual filetype with the `:set filetype` command. Could you tell me the result?

- What is the value of the `indentexpr` in that buffer? You can find that out using `:set indentexpr`.

- What is the version of Vim you're using? Html indentation has had some changes over the years that might affect this.

**Comment by alexlafroscia** [comment]
It seems like somewhere between February and now, this particular issue might be resolved.  I really appreciate your offer though, @AndrewRadev!

Just to be thorough, the `filetype` is `html.handlebars`, the `indentexpr` is set to `GetHandlebarsIndent()` and I'm using Neovim 0.1.7.

**Comment by AndrewRadev** [comment]
It might be the version of Vim or something like that. If you were using an older version at the time (or hadn't switched to neovim at the time), the html indent might not have been compatible for whatever reason.

Either way, if it's fixed, it might be a good idea to close the issue, but it's your issue, so feel free to take some time to figure it out, if you'd like :).

**Comment by nkgm** [comment]
@AndrewRadev is this meant to work with re-indent (`=`) also?  This for example:
```
{{#bs-navbar type=(if inverse 'inverse') fluid=fluid as |navbar|}}
 <div class="navbar-header">
      {{#link-to "index" class="navbar-brand"}}Brandy{{/link-to}}
  </div>
  {{#navbar.content}}
      {{#navbar.nav as |nav|}}
          {{#nav.item}}{{#nav.link-to "index"}}Home{{/nav.link-to}}{{/nav.item}}
          {{#nav.item}}{{#nav.link-to "demo.navbars"}}Navbars{{/nav.link-to}}{{/nav.item}}
      {{/navbar.nav}}
  {{/navbar.content}}
{{/bs-navbar}}
```

There seem to be a few such plugins out and about. Which ones (if any) would you recommend for Ember development?

**Comment by AndrewRadev** [comment]
Trying it out, I think the problem with reindenting with this plugin in this case is due to problems with single-line block components. The result in my tests is:

``` handlebars
{{#bs-navbar type=(if inverse 'inverse') fluid=fluid as |navbar|}}
  <div class="navbar-header">
    {{#link-to "index" class="navbar-brand"}}Brandy{{/link-to}}
    </div>
    {{#navbar.content}}
      {{#navbar.nav as |nav|}}
        {{#nav.item}}{{#nav.link-to "index"}}Home{{/nav.link-to}}{{/nav.item}}
          {{#nav.item}}{{#nav.link-to "demo.navbars"}}Navbars{{/nav.link-to}}{{/nav.item}}
          {{/navbar.nav}}
        {{/navbar.content}}
      {{/bs-navbar}}
```
I have a PR that fixes this: #53. I also have a fork where I have that and one more feature implemented: https://github.com/AndrewRadev/vim-mustache-handlebars

As for recommendations, what I use is the master branch of my own fork of this plugin. I don't really know of other plugins that do the same, so I can't really recommend anything else.

**Comment by nkgm** [comment]
Had a few misadventures with polyglot, but got it to work in the end and it looks great! Maybe consider opening the issue tracker - just a thought :)

**Comment by AndrewRadev** [comment]
Good point, I had forgotten that forks don't seem to have issues. I've enabled issues on my fork, so feel free to open any, if you find problems :).

As for polyglot, I think it just packages this plugin, or at least that's what I see from the README.
